### ISSUE TITLE
Failed to install version 0.3.0

### ISSUE THREAD

**Issue by GergelyMolnar** [big-o/cherrypicker#3]
As the title says:
```sh
(venv) $ pip install cherrypicker
Collecting cherrypickerout with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached cherrypicker-0.3.0.tar.gz (35 kB)s 
    ERROR: Command errored out with exit status 1:
     command: /home/gmolnar/*******/****/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-01qw4x2w/cherrypicker/setup.py'"'"'; __file__='"'"'/tmp/pip-install-01qw4x2w/cherrypicker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dbq8kg0u
         cwd: /tmp/pip-install-01qw4x2w/cherrypicker/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-01qw4x2w/cherrypicker/setup.py", line 61, in <module>
        'dev': parse_requirements('requirements-dev.txt'),
      File "/tmp/pip-install-01qw4x2w/cherrypicker/setup.py", line 33, in parse_requirements
        with open(filename, encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

```sh
$ uname -a 
Linux *** 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```sh
$ python3 --version
Python 3.6.8
```

ALTHOUGH version installs just fine:

```sh
$ pip install cherrypicker==0.2.2
Collecting cherrypicker==0.2.2
  Downloading cherrypicker-0.2.2.tar.gz (35 kB)
Collecting joblib>=0.13.0
  Downloading joblib-0.15.1-py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 1.8 MB/s 
Building wheels for collected packages: cherrypicker
  Building wheel for cherrypicker (setup.py) ... done
  Created wheel for cherrypicker: filename=cherrypicker-0.2.2-py3-none-any.whl size=12816 sha256=85bec2905ac4e8e59ff289a35712c8b2c9729d9314e0c4b30b8c961e62764352
  Stored in directory: /home/gmolnar/.cache/pip/wheels/47/5c/52/ed4e614e261963e123b9c81b1f1a2337f13d9217acb95a4343
Successfully built cherrypicker
Installing collected packages: joblib, cherrypicker
Successfully installed cherrypicker-0.2.2 joblib-0.15.1
```

**Comment by sprutzli** [comment]
I just ran into the same problem.

**Comment by big-o** [comment]
Oops - I missed a file from `MANIFEST.in`. Will release v0.3.1 which should fix this.
